version: '3'

services: 
  node:
    build: .
    volumes: 
      - .:/app
    ports: 
      - 3001:3000
    depends_on: 
      - db
  
  db:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    volumes: 
      - .docker/dbdata:/var/lib/mysql